name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Publish
      run: dotnet publish -c Release -r linux-x64 --self-contained true --version-suffix 0.9.0 -p:PublishSingleFile=true; dotnet publish -c Release -r win-x64 --self-contained true --version-suffix 0.9.0 -p:PublishSingleFile=true
