name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Publish
      run: dotnet publish -c Release -r linux-x64 --self-contained true --version-suffix 0.9.0 -p:PublishSingleFile=true
#    - name: Configure testing environment
#      run: mkdir -p ~/.minecraft/mods; mkdir -p ~/.minecraft/.fabric/remappedJars; touch ~/.minecraft/.fabric/remappedJars/minecraft-1.18.1-0.12.12.jar
#    - name: Test 
#      run: dotnet test; 
